[project]
name = "diann-analysis"
version = "0.1.0"
description = "Script for analyze diann output"
authors = [
    {name = "Chunhui Gu", email = "fduguchunhui@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyarrow>=19.0.1,<20.0.0",
    "pandas>=2.2.3,<3.0.0",
    "click>=8.1.0,<9.0.0",
]

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["src*"]

[project.scripts]
diann-analysis = "src.cli:cli"

