#BSUB -J diann-37
#BSUB -W 24:00 
#BSUB -o diann/log/library.out
#BSUB -e diann/log/library.err
#BSUB -cwd /rsrch5/scratch/ccp/hanash/Hanash_GPFS/Chunhui
#BSUB -q medium
#BSUB -n 28
#BSUB -M 350
#BSUB -R "rusage[mem=100]"
#BSUB -B 
#BSUB -N
#BSUB -u cgu3@mdanderson.org

echo $(hostname)
pwd


singularity exec --bind /rsrch5/scratch/ccp/hanash/Hanash_GPFS/Chunhui:/mnt diann/diann-1.9.1.img /diann-1.9.1/diann-linux \
--f /mnt/DIANN_Testing/IPAS8000/IPAS8001_PL396_IgB_V074_S4-F10_1_2684.d \
--lib "/mnt/DIANN_Testing/library/UNIPROT_human_revi_2024_12_19_ProteinAG_unimod37_phosphoSTY.predicted.speclib" \
--threads 48 --verbose 1 \
--out /mnt/DIANN_Testing/output/IPAS8000_diann37_UNIPROT_human_revi_2024_12_19_ProteinAG/IPAS8001_PL396_IgB_V074_S4-F10_1_2684/IPAS8001_PL396_IgB_V074_S4-F10_1_2684_report.tsv \
--qvalue 0.01 --matrices \
--temp  /mnt/DIANN_Testing/temp/IPAS8001_PL396_IgB_V074_S4-F10_1_2684 \
--out-lib /mnt/DIANN_Testing/output/IPAS8000_diann37_UNIPROT_human_revi_2024_12_19_ProteinAG/IPAS8001_PL396_IgB_V074_S4-F10_1_2684/IPAS8001_PL396_IgB_V074_S4-F10_1_2684_report-lib.parquet \
--gen-spec-lib --predictor \
--unimod4 --var-mods 5 --var-mod UniMod:35,15.994915,M --mass-acc 10 --mass-acc-ms1 15 --reanalyse --relaxed-prot-inf --rt-profiling --var-mod UniMod:37,42.046950,KR